export enum Platform {
  WHATSAPP = 'WHATSAPP',
  FACEBOOK = 'FACEBOOK',
  MESSENGER = 'MESSENGER',
  TELEGRAM = 'TELEGRAM',
  EMAIL = 'EMAIL',
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE',
  OTHER = 'OTHER',
}
