export enum NotificationType {
  DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS',
  WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  MANUAL = 'MANUAL',
  BROADCAST = 'BROADCAST',
}
