export enum NotificationType {
  DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS',
  WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  MANUAL = 'MANUAL',
  BROADCAST = 'BROADCAST',
}
